import "./globals.css";

export const metadata = {
  title: "My Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased leading-8 overflow-x-hidden bg-black">
        {children}
      </body>
    </html>
  );
}
